# for creating post:
# - 1) just go to _post folder and creating md file (like default) -be sure its name is look like defaults-
# - 2) fill the objects which of top of the page
# - 3) just writing something
# thats it!

title: "0xtrace"
description: "no pwn no life"
baseurl: https://00xtrace.github.io/
url: "https://00xtrace.github.io/"


# for navigation
links:
  - name: About
    link: /about
  - name: Blog
    link: /blog

configuration:
  display: #this is for showing sections
    usage: true # this mean the usage section is enable 
    index_helper: true # which of: "Go to _config.yml for..."

social_links:
  github: "https://github.com/00xtrace"
  twitter: "https://www.twitter.com/0xtr4ce"
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
